### PR TITLE
More geoprocessor classes for the following data:

### PR DESCRIPTION
**Pull request by mbertrand**
USGS Earthquake feed
GDACS (Global Disaster Alert Coordination System)
NASA GPM (Global Precipitation Measurement)
SPIE (Standardised Precipitation-Evapotranspiration Index) Drought Monitor

### CODE REVIEW

**Comment by aashish24** [comment]
@mbertrand this is nice! any preferred way for me to test it? I will review the code today.

**Comment by mbertrand** [comment]
@aashish24 there are some basic unit tests that can be run after dataqs is installed within a geonode instance: "python manage.py test dataqs".  Each processor can also be run by calling the script, such as "python ~/venvs/geonode/src/dataqs/dataqs/gfms/gfms.py".  I am workin now on updating minerva's dataservices code to include the new processors.  PS, one of the processors (SPEI) requires additional dependencies to convert from NetCDF format to GeoTIFF, I'll add that to the README.

**Comment by mbertrand** [comment]
Also, some of the geoprocessors require logins to retrieve the data (AirNow, NASA GPM)

**Comment by mbertrand** [comment]
@aashish24 @jbeezley Some changes to minerva dataservices to bring in new processors: https://github.com/Kitware/minerva/compare/minerva-geonode...minerva-geonode_mb?expand=1

**Comment by mbertrand** [comment]
@aashish24 are you ok with merging this into master?

**Comment by aashish24** [comment]
@mbertrand yes +1. I didn't run the code but looked at it. LGTM :+1:

**Comment by aashish24** [comment]
@mbertrand should we create  RTD for dataqs?

**Comment by mbertrand** [comment]
I suppose we could, though not sure if there's much to add beyond what's in the README.

**Comment by aashish24** [comment]
> I suppose we could, though not sure if there's much to add beyond what's in the README.

I was thinking more of a user/developer documentation. What we have is admin docs. Not a high priority though.

**Pull request merged**
