### PR TITLE
More HIFLD layers

### PR DESCRIPTION
**Pull request by mbertrand**
Added the following to the HIFLD_LAYERS property in the ansible dataq_settings.py template file:

EPA Emergency Response (ER) Risk Management Plan (RMP) Facilities
EPA Emergency Response (ER) Toxic Release Inventory (TRI) Facilities
US Hospitals
US Pharmacies
Hazardous Materials Routes

Note: Probably should merge the 'descriptions' PR first (https://github.com/OpenGeoscience/dataqs/pull/30)

### CODE REVIEW

**Comment by aashish24** [comment]
@mbertrand can you update this branch?

**Comment by mbertrand** [comment]
@aashish I updated it

**Comment by aashish24** [comment]
thanks LGTM :+1:

**Review by aashish24 — COMMENTED** [review]
LGTM

**Pull request merged**
