### PR TITLE
Update landscan style to hide no data values

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@doutriaux1 please review.

**Comment by aashish24** [comment]
@dorukozturk do you know the unit used in landscan data?

**Comment by dorukozturk** [comment]
@aashish24 According to the FAQ it is "The dataset values are people per cell.".

**Comment by aashish24** [comment]
sure but people per cell are in "millions" "thousands" etc?

**Pull request merged**
