### PR TITLE
University of Delaware Air Temp and Precipitation Processor

### PR DESCRIPTION
**Pull request by mbertrand**
Imports data from http://www.esrl.noaa.gov/psd/data/gridded/data.UDel_AirT_Precip.html into GeonNode/Geoserver.

### CODE REVIEW

**Comment by mbertrand** [comment]
@aashish24 I rebased this PR branch with master today

**Comment by aashish24** [comment]
I didn't run the code but it looks reasonable to me. +2

**Comment by aashish24** [comment]
However this is a conflict.

**Comment by mbertrand** [comment]
@aashish24 conflicts have been resolved for now.

**Pull request merged**
